// ============================================
// COURSE DATA - Generated by eLearning Platform
// SCORM Package: hjhj
// Generated: 2026-05-10T13:51:02.410613
// ============================================

// Define courseData as a global variable
// This will be safely initialized by the player
var courseData = {
  "courseId": "course_1778401141886",
  "exportContractVersion": "2026-04-12.1",
  "title": "hjhj",
  "author": "Course Author",
  "version": "1.0.0",
  "language": "en",
  "supportedTemplateTypes": [
    "accordion",
    "analytics-view",
    "branching-scenario",
    "breadcrumb",
    "calculator",
    "code-snippet",
    "content",
    "content-image",
    "content-media",
    "content-text",
    "content-video",
    "course-map",
    "course-menu",
    "data-visualization",
    "decision-tree",
    "drag-and-drop",
    "fill-in-blank",
    "flashcard",
    "form",
    "heat-map",
    "hotspot",
    "image-hotspots",
    "infographic",
    "interactive-tool",
    "key-takeaways",
    "learning-objectives",
    "learning-roadmap",
    "matching",
    "mcq",
    "metric",
    "module-overview",
    "multiple-select",
    "progress-tracker",
    "quiz",
    "quotation",
    "rich-text-editor",
    "role-play",
    "scenario",
    "sidebar-navigation",
    "stepper",
    "summary-takeaways",
    "tabs",
    "timeline",
    "transcript-caption",
    "true-false"
  ],
  "templates": [
    {
      "id": "54f2691c-29d4-4882-a6f3-85f9c5b3c753",
      "type": "content-media",
      "order": 0,
      "title": "Text with Media",
      "data": {
        "content": "Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.",
        "subtitle": null,
        "videoUrl": null,
        "questions": null,
        "tabs": null,
        "panels": null,
        "body": "Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.Understanding Cyber Threats\nLearn the basics of modern cyber risks, attack methods, and employee responsibilities.",
        "mediaUrl": "",
        "mediaType": "image",
        "mediaPosition": "right"
      },
      "pageId": "7aaaad12-b3c4-45b7-87b5-339cd164f003"
    }
  ],
  "totalSlides": 1,
  "createdAt": "2026-05-10T08:21:02.381254"
};

// Validation check
if (typeof courseData !== 'object' || !courseData.templates) {
    console.error('ERROR: courseData not properly loaded');
    console.error('courseData type:', typeof courseData);
    console.error('courseData value:', courseData);
    throw new Error('Course data initialization failed');
}

console.log('✓ Course data loaded successfully');
console.log('  Slides:', courseData.templates.length);
console.log('  Title:', courseData.title);
