// ============================================
// COURSE DATA - Generated by eLearning Platform
// SCORM Package: test
// Generated: 2026-05-10T10:31:04.052969
// ============================================

// Define courseData as a global variable
// This will be safely initialized by the player
var courseData = {
  "courseId": "course_1778387951760",
  "exportContractVersion": "2026-04-12.1",
  "title": "test",
  "author": "Course Author",
  "version": "1.0.0",
  "language": "en",
  "supportedTemplateTypes": [
    "accordion",
    "analytics-view",
    "branching-scenario",
    "breadcrumb",
    "calculator",
    "code-snippet",
    "content",
    "content-image",
    "content-media",
    "content-text",
    "content-video",
    "course-map",
    "course-menu",
    "data-visualization",
    "decision-tree",
    "drag-and-drop",
    "fill-in-blank",
    "flashcard",
    "form",
    "heat-map",
    "hotspot",
    "image-hotspots",
    "infographic",
    "interactive-tool",
    "key-takeaways",
    "learning-objectives",
    "learning-roadmap",
    "matching",
    "mcq",
    "metric",
    "module-overview",
    "multiple-select",
    "progress-tracker",
    "quiz",
    "quotation",
    "rich-text-editor",
    "role-play",
    "scenario",
    "sidebar-navigation",
    "stepper",
    "summary-takeaways",
    "tabs",
    "timeline",
    "transcript-caption",
    "true-false"
  ],
  "templates": [
    {
      "id": "4451f5b8-b87a-4375-82e9-5d60412214e0",
      "type": "content-media",
      "order": 0,
      "title": "Text with Media",
      "data": {
        "content": "<div style=\"display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:20px;margin-top:40px;\">\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Understanding Cyber Threats</h3>\n<p>Learn the basics of modern cyber risks, attack methods, and employee responsibilities.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Protecting Accounts and Devices</h3>\n<p>Understand password security, MFA, and secure device management practices.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Recognizing Social Engineering</h3>\n<p>Identify phishing, impersonation scams, and manipulation tactics used by attackers.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Handling Data Securely</h3>\n<p>Learn secure data storage, sharing, and confidentiality best practices.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Responding to Incidents</h3>\n<p>Discover how to recognize, report, and respond to cybersecurity incidents quickly.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Assessment &amp; Certification</h3>\n<p>Complete quizzes and a final assessment to earn course certification.</p>\n</div>\n</div>",
        "subtitle": null,
        "videoUrl": null,
        "questions": null,
        "tabs": null,
        "panels": null,
        "body": "<div style=\"display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:20px;margin-top:40px;\">\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Understanding Cyber Threats</h3>\n<p>Learn the basics of modern cyber risks, attack methods, and employee responsibilities.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Protecting Accounts and Devices</h3>\n<p>Understand password security, MFA, and secure device management practices.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Recognizing Social Engineering</h3>\n<p>Identify phishing, impersonation scams, and manipulation tactics used by attackers.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Handling Data Securely</h3>\n<p>Learn secure data storage, sharing, and confidentiality best practices.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Responding to Incidents</h3>\n<p>Discover how to recognize, report, and respond to cybersecurity incidents quickly.</p>\n</div>\n<div style=\"padding:24px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc;\">\n<h3 style=\"margin-top:0;color:#1e40af;\">Assessment &amp; Certification</h3>\n<p>Complete quizzes and a final assessment to earn course certification.</p>\n</div>\n</div>",
        "mediaUrl": "",
        "mediaType": "image",
        "mediaPosition": "right"
      },
      "pageId": "ec6b3f3d-6813-4272-83b4-08f4d27558a4"
    }
  ],
  "totalSlides": 1,
  "createdAt": "2026-05-10T05:01:04.028278"
};

// Validation check
if (typeof courseData !== 'object' || !courseData.templates) {
    console.error('ERROR: courseData not properly loaded');
    console.error('courseData type:', typeof courseData);
    console.error('courseData value:', courseData);
    throw new Error('Course data initialization failed');
}

console.log('✓ Course data loaded successfully');
console.log('  Slides:', courseData.templates.length);
console.log('  Title:', courseData.title);
