// ============================================
// COURSE DATA - Generated by eLearning Platform
// SCORM Package: thyrtrt
// Generated: 2026-05-10T14:30:18.100774
// ============================================

// Define courseData as a global variable
// This will be safely initialized by the player
var courseData = {
  "courseId": "course_1778403562385",
  "exportContractVersion": "2026-04-12.1",
  "title": "thyrtrt",
  "author": "Course Author",
  "version": "1.0.0",
  "language": "en",
  "supportedTemplateTypes": [
    "accordion",
    "analytics-view",
    "branching-scenario",
    "breadcrumb",
    "calculator",
    "code-snippet",
    "content",
    "content-image",
    "content-media",
    "content-text",
    "content-video",
    "course-map",
    "course-menu",
    "data-visualization",
    "decision-tree",
    "drag-and-drop",
    "fill-in-blank",
    "flashcard",
    "form",
    "heat-map",
    "hotspot",
    "image-hotspots",
    "infographic",
    "interactive-tool",
    "key-takeaways",
    "learning-objectives",
    "learning-roadmap",
    "matching",
    "mcq",
    "metric",
    "module-overview",
    "multiple-select",
    "progress-tracker",
    "quiz",
    "quotation",
    "rich-text-editor",
    "role-play",
    "scenario",
    "sidebar-navigation",
    "stepper",
    "summary-takeaways",
    "tabs",
    "timeline",
    "transcript-caption",
    "true-false"
  ],
  "templates": [
    {
      "id": "b4099514-2225-4995-8dbb-b0653d08f755",
      "type": "content-media",
      "order": 0,
      "title": "Text with Media",
      "data": {
        "content": "sdfgfgdfdfg",
        "subtitle": null,
        "videoUrl": null,
        "questions": null,
        "tabs": null,
        "panels": null,
        "body": "sdfgfgdfdfg",
        "mediaUrl": "",
        "mediaType": "image",
        "mediaPosition": "right"
      },
      "pageId": "d422b214-03a1-4d06-9432-ff6c2a6617cb"
    }
  ],
  "totalSlides": 1,
  "createdAt": "2026-05-10T09:00:18.079943"
};

// Validation check
if (typeof courseData !== 'object' || !courseData.templates) {
    console.error('ERROR: courseData not properly loaded');
    console.error('courseData type:', typeof courseData);
    console.error('courseData value:', courseData);
    throw new Error('Course data initialization failed');
}

console.log('✓ Course data loaded successfully');
console.log('  Slides:', courseData.templates.length);
console.log('  Title:', courseData.title);
