// ============================================
// COURSE DATA - Generated by eLearning Platform
// SCORM Package: prakash
// Generated: 2025-11-23T19:06:21.995265
// ============================================

// Define courseData as a global variable
// This will be safely initialized by the player
var courseData = {
  "courseId": "course_1763953407673",
  "title": "prakash",
  "author": "Unknown Author",
  "version": "1.0.0",
  "language": "en",
  "templates": [
    {
      "id": "page_1763953407673_1",
      "type": "content-text",
      "order": 0,
      "title": "Prakash Course Introduction",
      "data": {
        "content": "This course talk about light"
      }
    },
    {
      "id": "page_1763953407673_2",
      "type": "content-text",
      "order": 1,
      "title": "Virtual Lab Setup",
      "data": {
        "content": "You need Java\n......\nyou xyz\n......"
      }
    },
    {
      "id": "page_1763953407673_3",
      "type": "content-text",
      "order": 2,
      "title": "Course Introduction",
      "data": {
        "content": "Course contents"
      }
    },
    {
      "id": "page_1763953407673_4",
      "type": "mcq",
      "order": 3,
      "title": "Quiz Assessment",
      "data": {
        "content": "Quiz",
        "questions": [
          {
            "id": "q_page_1763953407673_4",
            "question": "Q1",
            "options": [
              {
                "id": "opt_0",
                "text": "a",
                "isCorrect": false
              },
              {
                "id": "opt_1",
                "text": "b",
                "isCorrect": false
              },
              {
                "id": "opt_2",
                "text": "cd",
                "isCorrect": true
              },
              {
                "id": "opt_3",
                "text": "d",
                "isCorrect": false
              }
            ]
          }
        ]
      }
    },
    {
      "id": "page_1763953407673_5",
      "type": "mcq",
      "order": 4,
      "title": "Quiz Assessment",
      "data": {
        "content": "Quiz",
        "questions": [
          {
            "id": "q_page_1763953407673_5",
            "question": "abc",
            "options": [
              {
                "id": "opt_0",
                "text": "x",
                "isCorrect": false
              },
              {
                "id": "opt_1",
                "text": "y",
                "isCorrect": false
              },
              {
                "id": "opt_2",
                "text": "z",
                "isCorrect": true
              },
              {
                "id": "opt_3",
                "text": "zz",
                "isCorrect": false
              }
            ]
          }
        ]
      }
    }
  ],
  "totalSlides": 5,
  "createdAt": "2025-11-24T03:06:21.986117"
};

// Validation check
if (typeof courseData !== 'object' || !courseData.templates) {
    console.error('ERROR: courseData not properly loaded');
    console.error('courseData type:', typeof courseData);
    console.error('courseData value:', courseData);
    throw new Error('Course data initialization failed');
}

console.log('✓ Course data loaded successfully');
console.log('  Slides:', courseData.templates.length);
console.log('  Title:', courseData.title);
